import { InventoryItem } from "../../domain/entities/inventory-item.entity";
import { WarehouseLocation } from "../../domain/entities/inventory-location.entity";
import { InventoryMovement } from "../../domain/entities/inventory-movement.entity";
import { StockReceipt } from "../../domain/entities/stock-receipt.entity";
import { StockIssue } from "../../domain/entities/stock-issue.entity";
import { StockReservation } from "../../domain/entities/stock-reservation.entity";
import { StockTransfer } from "../../domain/entities/stock-transfer.entity";
import { StockCount } from "../../domain/entities/stock-count.entity";
import { StockAdjustment } from "../../domain/entities/stock-adjustment.entity";

export function createPreSeededLocations(tenantId = "tenant-001"): WarehouseLocation[] {
  return [
    new WarehouseLocation({
      id: "loc-wh-main",
      tenantId,
      name: "انبار مرکزی و دپوی سنگ شمس‌آباد",
      code: "WH-MAIN",
      type: "WAREHOUSE",
      capacitySqm: 30000,
      currentUsageSqm: 4525,
      status: "ACTIVE",
      description: "انبار اصلی کارخانه واقع در شهرک صنعتی شمس‌آباد، مجهز به جرثقیل سقفی ۲۵ تن",
      createdAt: "۱۴۰۳/۰۱/۱۵",
      updatedAt: "۱۴۰۳/۰۶/۱۰",
    }),
    new WarehouseLocation({
      id: "loc-hall-a",
      tenantId,
      name: "سوله A (اسلب‌های صادراتی و بوک‌مچ)",
      code: "HALL-A",
      parentId: "loc-wh-main",
      parentName: "انبار مرکزی و دپوی سنگ شمس‌آباد",
      type: "HALL",
      capacitySqm: 8000,
      currentUsageSqm: 1700,
      status: "ACTIVE",
      description: "نگهداری اسلب‌های فرآوری شده با توری و رزین اپوکسی",
      createdAt: "۱۴۰۳/۰۱/۱۵",
      updatedAt: "۱۴۰۳/۰۶/۱۰",
    }),
    new WarehouseLocation({
      id: "loc-rack-a01",
      tenantId,
      name: "خرک اسلب A01 (مرمریت کالاتا)",
      code: "RCK-A01",
      parentId: "loc-hall-a",
      parentName: "سوله A",
      type: "RACK",
      capacitySqm: 1200,
      currentUsageSqm: 840,
      status: "ACTIVE",
      description: "خرک دوطرفه ویژه اسلب‌های سایز بزرگ",
      createdAt: "۱۴۰۳/۰۱/۱۵",
      updatedAt: "۱۴۰۳/۰۶/۱۰",
    }),
    new WarehouseLocation({
      id: "loc-rack-a02",
      tenantId,
      name: "خرک اسلب A02 (تراورتن آتشکوه)",
      code: "RCK-A02",
      parentId: "loc-hall-a",
      parentName: "سوله A",
      type: "RACK",
      capacitySqm: 1000,
      currentUsageSqm: 650,
      status: "ACTIVE",
      description: "خرک اسلب‌های سوپر آتشکوه",
      createdAt: "۱۴۰۳/۰۱/۱۵",
      updatedAt: "۱۴۰۳/۰۶/۱۰",
    }),
    new WarehouseLocation({
      id: "loc-rack-a05",
      tenantId,
      name: "خرک اسلب A05 (مرمر سبز انیکس)",
      code: "RCK-A05",
      parentId: "loc-hall-a",
      parentName: "سوله A",
      type: "RACK",
      capacitySqm: 500,
      currentUsageSqm: 210,
      status: "ACTIVE",
      description: "خرک پددار محافظت شده ویژه اسلب‌های شکننده مرمر",
      createdAt: "۱۴۰۳/۰۱/۱۵",
      updatedAt: "۱۴۰۳/۰۶/۱۰",
    }),
    new WarehouseLocation({
      id: "loc-hall-b",
      tenantId,
      name: "سوله B (تایل و پالت‌های بسته‌بندی)",
      code: "HALL-B",
      parentId: "loc-wh-main",
      parentName: "انبار مرکزی",
      type: "HALL",
      capacitySqm: 10000,
      currentUsageSqm: 2455,
      status: "ACTIVE",
      description: "سوله سرپوشیده ویژه نگهداری تایل‌های بسته‌بندی شده روی پالت چوبی شرینک شده",
      createdAt: "۱۴۰۳/۰۱/۱۵",
      updatedAt: "۱۴۰3/06/10",
    }),
    new WarehouseLocation({
      id: "loc-rack-b01",
      tenantId,
      name: "پالت‌های B01 (تراورتن عباس‌آباد نما)",
      code: "RCK-B01",
      parentId: "loc-hall-b",
      parentName: "سوله B",
      type: "RACK",
      capacitySqm: 2000,
      currentUsageSqm: 1450,
      status: "ACTIVE",
      createdAt: "۱۴۰۳/۰۱/۱۵",
      updatedAt: "۱۴۰۳/۰۶/۱۰",
    }),
    new WarehouseLocation({
      id: "loc-rack-b02",
      tenantId,
      name: "پالت‌های B02 (مرمریت دهبید رویال)",
      code: "RCK-B02",
      parentId: "loc-hall-b",
      parentName: "سوله B",
      type: "RACK",
      capacitySqm: 1500,
      currentUsageSqm: 920,
      status: "ACTIVE",
      createdAt: "۱۴۰۳/۰۱/۱۵",
      updatedAt: "۱۴۰۳/۰۶/۱۰",
    }),
    new WarehouseLocation({
      id: "loc-rack-b03",
      tenantId,
      name: "پالت‌های B03 (مرمریت پیپترا گری طولی)",
      code: "RCK-B03",
      parentId: "loc-hall-b",
      parentName: "سوله B",
      type: "RACK",
      capacitySqm: 1000,
      currentUsageSqm: 85,
      status: "ACTIVE",
      createdAt: "۱۴۰۳/۰۱/۱۵",
      updatedAt: "۱۴۰۳/۰۶/۱۰",
    }),
    new WarehouseLocation({
      id: "loc-yard-01",
      tenantId,
      name: "محوطه روباز و دپوی بلوک و لاشه",
      code: "YARD-01",
      parentId: "loc-wh-main",
      parentName: "انبار مرکزی",
      type: "YARD",
      capacitySqm: 12000,
      currentUsageSqm: 380,
      status: "ACTIVE",
      description: "محوطه باز جهت دپوی کوپ خام و پالت‌های گرانیت فلیم با لودر و تاورکرین",
      createdAt: "۱۴۰۳/۰۱/۱۵",
      updatedAt: "۱۴۰۳/۰۶/۱۰",
    }),
  ];
}

export function createPreSeededInventoryItems(tenantId = "tenant-001"): InventoryItem[] {
  return [
    new InventoryItem({
      id: "inv-1",
      tenantId,
      productId: "prod-1",
      productName: "سنگ مرمریت کالاتا گلد بوک‌مچ",
      stoneType: "marble",
      color: "gold",
      finish: "polished",
      form: "slab",
      dimensions: "۳۲۰ × ۱۸۰ سانتی‌متر",
      thickness: 2,
      grade: "سوپر صادراتی",
      unit: "sqm",
      onHand: 840,
      reserved: 120,
      qualityCheck: 20,
      damaged: 15,
      scrap: 25,
      minThreshold: 200,
      locationId: "loc-rack-a01",
      locationCode: "RCK-A01",
      locationName: "خرک اسلب A01 (مرمریت کالاتا)",
      batchNumber: "BT-2026-0910-001",
      slabId: "SL-10052",
      unitCost: 8_500_000,
      unitPrice: 12_600_000,
      status: "AVAILABLE",
      primaryImage: "/test_images/stones/test_1.jpg",
      notes: "کوپ اختصاصی معدن کاشان با رگه‌های طلایی یکنواخت و بدون پوسیدگی",
      lastMovementAt: "۱۴۰۳/۰۶/۱۰",
      createdAt: "۱۴۰۳/۰۳/۱۵",
      updatedAt: "۱۴۰۳/۰۶/۱۰",
    }),
    new InventoryItem({
      id: "inv-2",
      tenantId,
      productId: "prod-2",
      productName: "تراورتن کرم آتشکوه موج‌دار",
      stoneType: "travertine",
      color: "cream",
      finish: "polished",
      form: "slab",
      dimensions: "۳۰۰ × ۱۷۰ سانتی‌متر",
      thickness: 2,
      grade: "سوپر ممتاز",
      unit: "sqm",
      onHand: 650,
      reserved: 50,
      qualityCheck: 10,
      damaged: 0,
      scrap: 18,
      minThreshold: 150,
      locationId: "loc-rack-a02",
      locationCode: "RCK-A02",
      locationName: "خرک اسلب A02 (تراورتن آتشکوه)",
      batchNumber: "BT-2026-0905-002",
      slabId: "SL-10088",
      unitCost: 4_200_000,
      unitPrice: 6_800_000,
      status: "AVAILABLE",
      primaryImage: "/test_images/stones/test_5.jpg",
      notes: "ساب عالی بدون بتونه‌ریزی عمیق، مناسب نمای ویلایی و مدرن",
      lastMovementAt: "۱۴۰۳/۰۶/۰۸",
      createdAt: "۱۴۰۳/۰۴/۰۱",
      updatedAt: "۱۴۰۳/۰۶/۰۸",
    }),
    new InventoryItem({
      id: "inv-3",
      tenantId,
      productId: "prod-3",
      productName: "تراورتن سفید عباس‌آباد تایل",
      stoneType: "travertine",
      color: "white",
      finish: "polished",
      form: "tile",
      dimensions: "۶۰ × ۶۰ سانتی‌متر",
      thickness: 1.8,
      grade: "سوپر صادراتی",
      unit: "sqm",
      onHand: 1450,
      reserved: 220,
      qualityCheck: 30,
      damaged: 25,
      scrap: 40,
      minThreshold: 300,
      locationId: "loc-rack-b01",
      locationCode: "RCK-B01",
      locationName: "پالت‌های B01 (تراورتن عباس‌آباد نما)",
      batchNumber: "BT-2026-0815-007",
      unitCost: 950_000,
      unitPrice: 1_450_000,
      status: "AVAILABLE",
      primaryImage: "/test_images/stones/test_2.jpg",
      notes: "بسته‌بندی پالت پلاستوفوم‌دار، آماده بارگیری با لیفتراک",
      lastMovementAt: "۱۴۰۳/۰۶/۰۹",
      createdAt: "۱۴۰۳/۰۲/۲۰",
      updatedAt: "۱۴۰۳/۰۶/۰۹",
    }),
    new InventoryItem({
      id: "inv-4",
      tenantId,
      productId: "prod-4",
      productName: "مرمر سبز انیکس لوکس (نورگذر)",
      stoneType: "onyx",
      color: "green",
      finish: "polished",
      form: "slab",
      dimensions: "۲۸۰ × ۱۵۰ سانتی‌متر",
      thickness: 2,
      grade: "لوکس صادراتی",
      unit: "sqm",
      onHand: 210,
      reserved: 40,
      qualityCheck: 15,
      damaged: 5,
      scrap: 10,
      minThreshold: 80,
      locationId: "loc-rack-a05",
      locationCode: "RCK-A05",
      locationName: "خرک اسلب A05 (مرمر سبز انیکس)",
      batchNumber: "BT-2026-0820-003",
      slabId: "SL-10114",
      unitCost: 16_000_000,
      unitPrice: 24_000_000,
      status: "AVAILABLE",
      primaryImage: "/test_images/stones/test_3.jpg",
      notes: "قابلیت عبور نور ۱۰۰٪، کالیبره شده با خط پولیش ایتالیایی",
      lastMovementAt: "۱۴۰۳/۰۶/۰۵",
      createdAt: "۱۴۰۳/۰۳/۰۱",
      updatedAt: "۱۴۰۳/۰۶/۰۵",
    }),
    new InventoryItem({
      id: "inv-5",
      tenantId,
      productId: "prod-5",
      productName: "مرمریت دهبید شایان رویال تایل",
      stoneType: "marble",
      color: "cream",
      finish: "polished",
      form: "tile",
      dimensions: "۸۰ × ۸۰ سانتی‌متر",
      thickness: 2,
      grade: "سوپر ممتاز",
      unit: "sqm",
      onHand: 920,
      reserved: 150,
      qualityCheck: 20,
      damaged: 10,
      scrap: 30,
      minThreshold: 200,
      locationId: "loc-rack-b02",
      locationCode: "RCK-B02",
      locationName: "پالت‌های B02 (مرمریت دهبید رویال)",
      batchNumber: "BT-2026-0828-005",
      unitCost: 1_200_000,
      unitPrice: 1_850_000,
      status: "AVAILABLE",
      primaryImage: "/test_images/stones/test_4.jpg",
      notes: "تراکم فوق‌العاده با ساب آینه‌ای مخصوص کف لابی و سالن پذیرایی",
      lastMovementAt: "۱۴۰۳/۰۶/۰۷",
      createdAt: "۱۴۰۳/۰۴/۱۰",
      updatedAt: "۱۴۰۳/۰۶/۰۷",
    }),
    new InventoryItem({
      id: "inv-6",
      tenantId,
      productId: "prod-6",
      productName: "گرانیت مشکی نطنز فلیم شیاردار",
      stoneType: "granite",
      color: "black",
      finish: "flamed",
      form: "tile",
      dimensions: "۴۰ × ۴۰ سانتی‌متر",
      thickness: 2,
      grade: "درجه یک",
      unit: "sqm",
      onHand: 380,
      reserved: 0,
      qualityCheck: 0,
      damaged: 12,
      scrap: 15,
      minThreshold: 100,
      locationId: "loc-yard-01",
      locationCode: "YARD-01",
      locationName: "محوطه روباز و دپوی بلوک و لاشه",
      batchNumber: "BT-2026-0710-009",
      unitCost: 750_000,
      unitPrice: 1_150_000,
      status: "AVAILABLE",
      primaryImage: "/test_images/stones/test_6.jpg",
      notes: "ضد لغزش (Non-slip) ویژه پیاده‌رو، رمپ و محوطه‌سازی بیرونی",
      lastMovementAt: "۱۴۰۳/۰۵/۲۸",
      createdAt: "۱۴۰۳/۰۲/۰۵",
      updatedAt: "۱۴۰۳/۰۵/۲۸",
    }),
    new InventoryItem({
      id: "inv-7",
      tenantId,
      productId: "prod-7",
      productName: "مرمریت لاشتر (پیترا گری) طولی",
      stoneType: "marble",
      color: "grey",
      finish: "honed",
      form: "cut-to-size",
      dimensions: "۴۰ طولی آزاد",
      thickness: 2,
      grade: "صادراتی سوپر",
      unit: "sqm",
      onHand: 85,
      reserved: 60,
      qualityCheck: 5,
      damaged: 8,
      scrap: 12,
      minThreshold: 100, // available is 25 <= 100 -> TRIGGER LOW STOCK ALERT!
      locationId: "loc-rack-b03",
      locationCode: "RCK-B03",
      locationName: "پالت‌های B03 (مرمریت پیپترا گری طولی)",
      batchNumber: "BT-2026-0812-004",
      unitCost: 1_800_000,
      unitPrice: 2_750_000,
      status: "AVAILABLE",
      primaryImage: "/test_images/stones/test_7.jpg",
      notes: "طوسی تیره مات با خطوط سپید منظم، در آستانه کسری انبار",
      lastMovementAt: "۱۴۰۳/۰۶/۱۰",
      createdAt: "۱۴۰۳/۰۵/۰۱",
      updatedAt: "۱۴۰۳/۰۶/۱۰",
    }),
  ];
}

export function createPreSeededMovements(tenantId = "tenant-001"): InventoryMovement[] {
  return [
    new InventoryMovement({
      id: "mov-1",
      tenantId,
      inventoryItemId: "inv-1",
      productName: "سنگ مرمریت کالاتا گلد بوک‌مچ",
      type: "RECEIPT",
      quantity: 500,
      unit: "sqm",
      destinationLocationId: "loc-rack-a01",
      destinationLocationName: "خرک اسلب A01",
      referenceType: "RECEIPT",
      referenceNumber: "REC-1403-01",
      balanceAfter: 840,
      reason: "ورود بار خط برش و اره اصفهان (کوپ ۶۰ تنی کالاتا)",
      performedBy: "مدیر انبار - مهندس راد",
      createdAt: "۱۴۰۳/۰۶/۱۰ ۱۱:۳۰",
    }),
    new InventoryMovement({
      id: "mov-2",
      tenantId,
      inventoryItemId: "inv-1",
      productName: "سنگ مرمریت کالاتا گلد بوک‌مچ",
      type: "RESERVATION_HOLD",
      quantity: 120,
      unit: "sqm",
      referenceType: "ORDER",
      referenceNumber: "ORD-94102",
      balanceAfter: 840,
      reason: "رزرو سفارش پروژه ویلای لواسان (آقای دکتر احمدی)",
      performedBy: "سیستم فروش آنلاین",
      createdAt: "۱۴۰۳/۰۶/۰۹ ۱۶:۴۵",
    }),
    new InventoryMovement({
      id: "mov-3",
      tenantId,
      inventoryItemId: "inv-3",
      productName: "تراورتن سفید عباس‌آباد تایل",
      type: "ISSUE",
      quantity: 150,
      unit: "sqm",
      sourceLocationId: "loc-rack-b01",
      sourceLocationName: "پالت‌های B01",
      referenceType: "ISSUE",
      referenceNumber: "ISS-1403-08",
      balanceAfter: 1450,
      reason: "بارگیری تریلی کفی به مقصد پروژه برج الهیه تهران",
      performedBy: "مسئول لجستیک - صادقی",
      createdAt: "۱۴۰۳/۰۶/۰۹ ۰۹:۱۵",
    }),
    new InventoryMovement({
      id: "mov-4",
      tenantId,
      inventoryItemId: "inv-2",
      productName: "تراورتن کرم آتشکوه موج‌دار",
      type: "TRANSFER_IN",
      quantity: 80,
      unit: "sqm",
      sourceLocationId: "loc-yard-01",
      sourceLocationName: "محوطه دپو",
      destinationLocationId: "loc-rack-a02",
      destinationLocationName: "خرک اسلب A02",
      referenceType: "TRANSFER",
      referenceNumber: "TRF-1403-03",
      balanceAfter: 650,
      reason: "انتقال اسلب‌های پولیش شده نهایی از محوطه ساب به سالن A",
      performedBy: "اپراتور لیفتراک - نوری",
      createdAt: "۱۴۰۳/۰۶/۰۸ ۱۴:۲۰",
    }),
    new InventoryMovement({
      id: "mov-5",
      tenantId,
      inventoryItemId: "inv-7",
      productName: "مرمریت لاشتر (پیترا گری) طولی",
      type: "ADJUSTMENT_OUT",
      quantity: 10,
      unit: "sqm",
      referenceType: "ADJUSTMENT",
      referenceNumber: "ADJ-1403-02",
      balanceAfter: 85,
      reason: "شکستگی ناشی از جابجایی غیراصولی پالت سنگ طولی",
      performedBy: "سرپرست کنترل کیفی - کاظمی",
      createdAt: "۱۴۰۳/۰۶/۰۷ ۱۷:۰۰",
    }),
  ];
}

export function createPreSeededReceipts(tenantId = "tenant-001"): StockReceipt[] {
  return [
    new StockReceipt({
      id: "rec-1",
      tenantId,
      receiptNumber: "REC-1403-01",
      source: "PRODUCTION",
      supplierName: "خط قله‌بر و خط تایل شماره ۲ کارخانه",
      status: "CONFIRMED",
      items: [
        {
          id: "ritem-1",
          inventoryItemId: "inv-1",
          productId: "prod-1",
          productName: "سنگ مرمریت کالاتا گلد بوک‌مچ",
          stoneType: "marble",
          dimensions: "۳۲۰ × ۱۸۰ سانتی‌متر",
          thickness: 2,
          grade: "سوپر صادراتی",
          batchNumber: "BT-2026-0910-001",
          slabId: "SL-10052",
          locationId: "loc-rack-a01",
          locationName: "خرک اسلب A01",
          quantity: 240,
          unit: "sqm",
          unitCost: 8_500_000,
          notes: "برش با سیم الماسه و پولیش خط برتون",
        },
      ],
      totalQuantity: 240,
      unit: "sqm",
      reference: "برگه تولید کارگاهی #۸۹۰۴",
      notes: "کیفیت ساب ۹۸ درصد، تحویل انباردار شد",
      receivedBy: "مدیر انبار - مهندس راد",
      confirmedAt: "۱۴۰۳/۰۶/۱۰ ۱۱:۳۰",
      createdAt: "۱۴۰۳/۰۶/۱۰ ۱۰:۰۰",
      updatedAt: "۱۴۰۳/۰۶/۱۰ ۱۱:۳۰",
    }),
    new StockReceipt({
      id: "rec-2",
      tenantId,
      receiptNumber: "REC-1403-02",
      source: "SUPPLIER",
      supplierName: "معدن تراورتن حاجی‌آباد محلات",
      status: "DRAFT",
      items: [
        {
          id: "ritem-2",
          productId: "prod-3",
          productName: "تراورتن سفید عباس‌آباد تایل",
          stoneType: "travertine",
          dimensions: "۶۰ × ۶۰ سانتی‌متر",
          thickness: 1.8,
          grade: "درجه یک",
          locationId: "loc-rack-b01",
          locationName: "پالت‌های B01",
          quantity: 350,
          unit: "sqm",
          unitCost: 900_000,
        },
      ],
      totalQuantity: 350,
      unit: "sqm",
      reference: "بارنامه کامیون ۴۸ ایران ۲۵",
      notes: "بار در مرحله تخلیه و ارزیابی تخلخل سطحی",
      receivedBy: "مسئول باسکول - حیدری",
      createdAt: "۱۴۰۳/۰۶/۱۲ ۰۸:۳۰",
      updatedAt: "۱۴۰۳/۰۶/۱۲ ۰۸:۳۰",
    }),
  ];
}

export function createPreSeededIssues(tenantId = "tenant-001"): StockIssue[] {
  return [
    new StockIssue({
      id: "iss-1",
      tenantId,
      issueNumber: "ISS-1403-08",
      reason: "ORDER_FULFILLMENT",
      orderId: "ord-8812",
      customerName: "شرکت ساختمانی سازه‌گستران پایدار",
      status: "CONFIRMED",
      items: [
        {
          id: "iitem-1",
          inventoryItemId: "inv-3",
          productId: "prod-3",
          productName: "تراورتن سفید عباس‌آباد تایل",
          stoneType: "travertine",
          locationId: "loc-rack-b01",
          locationName: "پالت‌های B01",
          quantity: 150,
          unit: "sqm",
          unitPrice: 1_450_000,
        },
      ],
      totalQuantity: 150,
      unit: "sqm",
      reference: "فاکتور رسمی ۹۰۴۵/الف",
      notes: "تسمه‌کشی با ضربه‌گیر چوبی دوبل",
      issuedBy: "مسئول لجستیک - صادقی",
      confirmedAt: "۱۴۰۳/۰۶/۰۹ ۰۹:۱۵",
      createdAt: "۱۴۰۳/۰۶/۰۹ ۰۸:۰۰",
      updatedAt: "۱۴۰۳/۰۶/۰۹ ۰۹:۱۵",
    }),
  ];
}

export function createPreSeededReservations(tenantId = "tenant-001"): StockReservation[] {
  return [
    new StockReservation({
      id: "res-1",
      tenantId,
      reservationNumber: "RES-1403-001",
      inventoryItemId: "inv-1",
      productId: "prod-1",
      productName: "سنگ مرمریت کالاتا گلد بوک‌مچ",
      stoneType: "marble",
      locationId: "loc-rack-a01",
      locationName: "خرک اسلب A01",
      quantity: 120,
      unit: "sqm",
      orderId: "ord-c-17415801",
      orderNumber: "ORD-94102",
      customerName: "دکتر مسعود احمدی",
      status: "ACTIVE",
      expiresAt: "۱۴۰۳/۰۶/۱۵",
      notes: "رزرو آنلاین سفارش کفپوش لابی عمارت نیاوران",
      createdBy: "سیستم فروش آنلاین",
      createdAt: "۱۴۰۳/۰۶/۰۹ ۱۶:۴۵",
      updatedAt: "۱۴۰۳/۰۶/۰۹ ۱۶:۴۵",
    }),
    new StockReservation({
      id: "res-2",
      tenantId,
      reservationNumber: "RES-1403-002",
      inventoryItemId: "inv-7",
      productId: "prod-7",
      productName: "مرمریت لاشتر (پیترا گری) طولی",
      stoneType: "marble",
      locationId: "loc-rack-b03",
      locationName: "پالت‌های B03",
      quantity: 60,
      unit: "sqm",
      customerName: "مهندس شریفی (معماری دیبا)",
      status: "ACTIVE",
      expiresAt: "۱۴۰۳/۰۶/۱۴",
      notes: "پیش‌فاکتور شماره ۸۲ - در انتظار تایید واریز بیعانه",
      createdBy: "مدیر فروش کارخانه",
      createdAt: "۱۴۰۳/۰۶/۱۰ ۱۰:۳۰",
      updatedAt: "۱۴۰۳/۰۶/۱۰ ۱۰:۳۰",
    }),
  ];
}

export function createPreSeededTransfers(tenantId = "tenant-001"): StockTransfer[] {
  return [
    new StockTransfer({
      id: "trf-1",
      tenantId,
      transferNumber: "TRF-1403-03",
      inventoryItemId: "inv-2",
      productName: "تراورتن کرم آتشکوه موج‌دار",
      stoneType: "travertine",
      sourceLocationId: "loc-yard-01",
      sourceLocationName: "محوطه دپو",
      destinationLocationId: "loc-rack-a02",
      destinationLocationName: "خرک اسلب A02",
      quantity: 80,
      unit: "sqm",
      status: "COMPLETED",
      reason: "تکمیل ساب و انتقال به سالن مسقف",
      transferredBy: "اپراتور لیفتراک - نوری",
      completedAt: "۱۴۰۳/۰۶/۰۸ ۱۴:۲۰",
      createdAt: "۱۴۰۳/۰۶/۰۸ ۱۳:۰۰",
      updatedAt: "۱۴۰۳/۰۶/۰۸ ۱۴:۲۰",
    }),
  ];
}

export function createPreSeededCounts(tenantId = "tenant-001"): StockCount[] {
  return [
    new StockCount({
      id: "cnt-1",
      tenantId,
      countNumber: "CNT-1403-01",
      title: "انبارگردانی فصلی تابستان سالن B (تایل‌ها)",
      locationId: "loc-hall-b",
      locationName: "سوله B (تایل و پالت‌های بسته‌بندی)",
      status: "COMPLETED",
      items: [
        {
          id: "citem-1",
          inventoryItemId: "inv-3",
          productName: "تراورتن سفید عباس‌آباد تایل",
          stoneType: "travertine",
          dimensions: "۶۰ × ۶۰",
          unit: "sqm",
          systemQuantity: 1455,
          physicalQuantity: 1450,
          discrepancyQuantity: -5,
          notes: "۵ متر کسری به دلیل شکستگی گوشه هنگام تخلیه",
        },
        {
          id: "citem-2",
          inventoryItemId: "inv-5",
          productName: "مرمریت دهبید شایان رویال تایل",
          stoneType: "marble",
          dimensions: "۸۰ × ۸۰",
          unit: "sqm",
          systemQuantity: 920,
          physicalQuantity: 920,
          discrepancyQuantity: 0,
        },
      ],
      totalSystemQty: 2375,
      totalPhysicalQty: 2370,
      totalDiffQty: -5,
      countedBy: "هیات شمارش: حسینی، قربانی، ناظر مالی شمس",
      completedAt: "۱۴۰۳/۰۶/۰۶ ۱۸:۰۰",
      notes: "شمارش دقیق پالت به پالت با بارکدخوان دستی",
      createdAt: "۱۴۰۳/۰۶/۰۶ ۰۸:۰۰",
      updatedAt: "۱۴۰۳/۰۶/۰۶ ۱۸:۰۰",
    }),
  ];
}

export function createPreSeededAdjustments(tenantId = "tenant-001"): StockAdjustment[] {
  return [
    new StockAdjustment({
      id: "adj-1",
      tenantId,
      adjustmentNumber: "ADJ-1403-02",
      inventoryItemId: "inv-7",
      productName: "مرمریت لاشتر (پیترا گری) طولی",
      quantityChange: -10,
      unit: "sqm",
      targetProperty: "onHand",
      reason: "شکستگی ناشی از جابجایی غیراصولی پالت سنگ طولی",
      referenceType: "REPORT",
      referenceNumber: "REP-QC-401",
      notes: "سنگ‌های شکسته به بخش لاشه و جدول باغچه محوطه انتقال یافت",
      adjustedBy: "سرپرست کنترل کیفی - کاظمی",
      createdAt: "۱۴۰۳/۰۶/۰۷ ۱۷:۰۰",
    }),
  ];
}
